### ISSUE TITLE
attain 1.0.6 is no longer working.

### ISSUE THREAD

**Issue by aaronwlee** [itays123/sunny-villas#1]
due to deno changed their package system, attain@1.0.6 is no longer accessible and supported.

please update to 1.0.10 version :)

"https://deno.land/x/attain@1.0.10/mod.ts" in serverDeps

```ts
import { useRouter } from "https://deno.land/x/attain@1.0.10/react/AttainRouter.js";
import {
  useDocument,
  addMeta,
  addScript,
  setTitle,
} from "https://deno.land/x/attain@1.0.10/react/AttainReactUtils.js";
```
 in /view/deps.tsx

also, types repo has been removed from the deno.land, the types should change to
```
// @deno-types="https://raw.githubusercontent.com/Soremwar/deno_types/master/react/v16.13.1/react.d.ts"
import React from "https://jspm.dev/react@16.13.1";

// @deno-types="https://raw.githubusercontent.com/Soremwar/deno_types/master/react-dom/v16.13.1/server.d.ts"
import ReactDOMServer from "https://jspm.dev/react-dom@16.13.1/server";

// @deno-types="https://raw.githubusercontent.com/Soremwar/deno_types/master/react-dom/v16.13.1/react-dom.d.ts"
import ReactDOM from "https://jspm.dev/react-dom@16.13.1";
```

**Comment by itays123** [comment]
Thank you!

**Comment by itays123** [comment]
this throws an error:
```
error: TS2300 [ERROR]: Duplicate identifier 'LibraryManagedAttributes'.
    type LibraryManagedAttributes<C, P> = C extends
         ~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/types/react/v16.13.1/react.d.ts:3294:10

    'LibraryManagedAttributes' was also declared here.
        type LibraryManagedAttributes<C, P> = C extends
             ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://raw.githubusercontent.com/Soremwar/deno_types/master/react/v16.13.1/react.d.ts:3294:10

TS2300 [ERROR]: Duplicate identifier 'LibraryManagedAttributes'.
    type LibraryManagedAttributes<C, P> = C extends
         ~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/Soremwar/deno_types/master/react/v16.13.1/react.d.ts:3294:10

    'LibraryManagedAttributes' was also declared here.
        type LibraryManagedAttributes<C, P> = C extends
             ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/types/react/v16.13.1/react.d.ts:3294:10
```
